server:
  port: 8071
---
management:
  server:
    port: 8061
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: "*"
    health:
      show-details: always
---
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 10.10.0.44
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://10.10.0.51:8761/eureka/
---
spring:
  application:
    name: bus-server
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.10.0.51:9092
          zkNodes: 10.10.0.51:2181/kafka
